config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :contacts

end

app/models/contact.rb
class Contact < ActiveRecord::Base
	has_many :contact_info
  	accepts_nested_attributes_for :contact_info, reject_if: :all_blank, allow_destroy: true
end

app/models/contact_info.rb
class ContactInfo < ActiveRecord::Base
	belongs_to :contact
end

app/models/info_type.rb
class InfoType < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

	def new
		@contact_list = Contact.new
	end

	def edit
		@contact_list = Contact.find(params[:id])
		@contact_list.contact_info.build
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@contact_list= Contact.all
	end

	

	def destroy
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/_cinfo.html.erb
<%= f.label :value %>
<%= f.text_field :value %>

app/views/contacts/edit.html.erb
<!--
    you can substitue the span of reauth email for a input with the email and
    include the remember me checkbox
    -->
    <div class="container">
        <div class="card card-container">
            <!-- <img class="profile-img-card" src="//lh3.googleusercontent.com/-6V8xOA6M7BA/AAAAAAAAAAI/AAAAAAAAAAA/rzlHcD0KYwo/photo.jpg?sz=120" alt="" /> -->

            <img id="profile-img" class="profile-img-card" src="//ssl.gstatic.com/accounts/ui/avatar_2x.png" />
           
           <%= form_for @contact_list do |f| %>

                <%= f.label :full_name %>
                <%= f.text_field :full_name, class: "form-control" %>
                <%= f.label :notes %>
                <%= f.text_field :notes, class: "form-control" %>

                <%= f.fields_for :contact_info do |cinfo| %>
                    <%= render 'cinfo_fields', f: cinfo %>
                    <%= link_to_add_association 'add info', f, :cinfo %>
                <% end %>

            <% end %>
        </div><!-- /card-container -->
    </div><!-- /container -->

app/views/home/index.html.erb
<a href="http://bootsnipp.com/mouse0270/snippets/4l0k2" class="btn btn-danger hide" id="back-to-bootsnipp">Back to Bootsnipp</a>

<div class="container">

    <div class="row">
        <div class="col-xs-12 col-sm-offset-3 col-sm-6">
            <div class="panel panel-default">
                <div class="panel-heading c-list">
                    <span class="title">Contacts (<%= @contact_list.size %>)</span>
                    <ul class="pull-right c-controls">
                        <li><a href="#cant-do-all-the-work-for-you" data-toggle="tooltip" data-placement="top" title="Add Contact"><i class="glyphicon glyphicon-plus"></i></a></li>
                        <li><a href="#" class="hide-search" data-command="toggle-search" data-toggle="tooltip" data-placement="top" title="Toggle Search"><i class="fa fa-ellipsis-v"></i></a></li>
                    </ul>
                </div>
                
                <div class="row" style="display: none;">
                    <div class="col-xs-12">
                        <div class="input-group c-search">
                            <input type="text" class="form-control" id="contact-list-search">
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="button"><span class="glyphicon glyphicon-search text-muted"></span></button>
                            </span>
                        </div>
                    </div>
                </div>
                
                <ul class="list-group" id="contact-list">

                    <% @contact_list.each do |m| %>
                    <li class="list-group-item">
                        <div class="col-xs-12 col-sm-3">
                            <img src="//ssl.gstatic.com/accounts/ui/avatar_2x.png" alt="Scott Stevens" class="img-responsive img-circle" />
                        </div>
                        <div class="col-xs-12 col-sm-9">
                            <span class="name"><%= m.full_name %></span><br/>
                            <%= link_to '' , contact_path(m), title: "Eliminar",  class: "glyphicon glyphicon-remove text-muted c-info", method: :delete %>
                            <%= link_to '' , edit_contact_path(m), title: "Editar",  class: "glyphicon glyphicon-pencil text-muted c-info" %>
                            <%= link_to '' , contact_path(m), title: "Ver",  class: "glyphicon glyphicon-search text-muted c-info" %>
                        </div>
                        <div class="clearfix"></div>
                    </li>
                    <% end %>
                </ul>
            </div>
        </div>
	</div>
    
    <div id="cant-do-all-the-work-for-you" class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title" id="mySmallModalLabel">Ooops!!!</h4>
                </div>
                <div class="modal-body">
                    <p>I am being lazy and do not want to program an "Add User" section into this snippet... So it looks like you'll have to do that for yourself.</p><br/>
                    <p><strong>Sorry<br/>
                    ~ Mouse0270</strong></p>
                </div>
            </div>
        </div>
    </div>
    
    <!-- JavaScrip Search Plugin -->
    <script src="//rawgithub.com/stidges/jquery-searchable/master/dist/jquery.searchable-1.0.0.min.js"></script>
    
</div>

app/views/layouts/_cinfo.html.erb
<%= f.label :value %>
<%= f.text_field :value %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ContactList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag :cocoon %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>